// This file is generated by scripts/generate-addons-registry.mjs.
// Do not edit it by hand.
import type { AddonRegistryEntry } from "./types";

export const addonRegistry: AddonRegistryEntry[] = [];
